name: benchmark

channels:
  - pytorch
  - conda-forge

# Add optional dependencies for `pytorch-lightning` as needed.
dependencies:
  - python=3.9
  - pip
  - pytorch=1.10.2
  - torchvision  # determined by pytorch
