name: benchmark

channels:
  - pytorch
  - conda-forge

# Add any optional dependencies for `pytorch-lightning`.
# Specify versions of PyTorch-related packages for robustness.
dependencies:
  - python=3.9
  - pip
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - pip:
      # strategies
      - hivemind
      - horovod
      - deepspeed<0.6.0
      - fairscale
      - bagua-cuda113
      # loggers
      - neptune-client
      - comet-ml
      - mlflow
      - wandb
      # extra
      - matplotlib
      - torchtext
      - omegaconf
      - hydra-core
      - jsonargparse[signatures]
      - gcsfs
      - rich
