[tool.isort]
src_paths = ["benchmarks"]
known_first_party = ["benchmarks", "pytorch_lightning"]
profile = "black"
line_length = 120
force_sort_within_sections = false
order_by_type = false

[tool.black]
line-length = 120
